const products = [
	{
		_id: "1",
		name: "Pink Retro Sunnies",
		image: "/images/image1.jpg",
		description: "Beautiful hot pink retro sunglasses",
		brand: "Qway",
		category: "Fashion",
		price: 9.99,
		countInStock: 10,
		rating: 4.5,
		numReviews: 12,
	},
	{
		_id: "2",
		name: "Clear Retro Glasses",
		image: "/images/image2.jpg",
		description: "Sometimes simplicity is best",
		brand: "LoveLorna",
		category: "Fashion",
		price: 10.99,
		countInStock: 7,
		rating: 4.0,
		numReviews: 8,
	},
	{
		_id: "3",
		name: "Pink Flamingo Ring Float",
		image: "/images/image3.jpg",
		description: "Adorably designed pool float",
		brand: "DaintyDesignz",
		category: "Swim",
		price: 29.99,
		countInStock: 5,
		rating: 3,
		numReviews: 12,
	},
	{
		_id: "4",
		name: "Set of 3 Multicolored Bowls",
		image: "/images/image4.jpg",
		description:
			"These beautiful mismatched bowls will be the perfect addition to any quirky kitchen",
		brand: "DaintyDesignz",
		category: "Kitchen",
		price: 19.99,
		countInStock: 11,
		rating: 5,
		numReviews: 12,
	},
	{
		_id: "5",
		name: "Retro Polaroid Camera",
		image: "/images/image5.jpg",
		description:
			"This retro camera is the perfect gift for the photographer in you",
		brand: "Polaroid",
		category: "Electronics",
		price: 79.99,
		countInStock: 7,
		rating: 3.5,
		numReviews: 10,
	},
	{
		_id: "6",
		name: "Pink Coffee Mug",
		image: "/images/image6.jpg",
		description: "Adorable baby pink coffee mug",
		brand: "Amaze",
		category: "Kitchen",
		price: 3.99,
		countInStock: 0,
		rating: 4,
		numReviews: 12,
	},
];

export default products;
